services:
    odiseo_sylius_referrals_plugin.custom_factory.affiliate_referral:
        class: Odiseo\SyliusReferralsPlugin\Factory\AffiliateReferralFactory
        decorates: odiseo_sylius_referrals_plugin.factory.affiliate_referral
        arguments:
            - '@odiseo_sylius_referrals_plugin.custom_factory.affiliate_referral.inner'
