services:
    odiseo_sylius_referrals_plugin.generator.affiliate:
        class: Odiseo\SyliusReferralsPlugin\Generator\AffiliateGenerator
        public: true
        arguments:
            - '@odiseo_sylius_referrals_plugin.factory.affiliate'
            - '@odiseo_sylius_referrals_plugin.repository.affiliate'
            - '@event_dispatcher'
