services:
    odiseo_sylius_referrals_plugin.generator.affiliate_referral:
        class: Odiseo\SyliusReferralsPlugin\Generator\AffiliateReferralGenerator
        public: true
        arguments:
            - '@odiseo_sylius_referrals_plugin.factory.affiliate_referral'
            - '@odiseo_sylius_referrals_plugin.repository.affiliate_referral'
            - '@event_dispatcher'
