winzou_state_machine:
    sylius_order:
        callbacks:
            after:
                odiseo_sylius_referrals_plugin_assign_affiliate_referral_on_order:
                    on: ["create"]
                    do: ["@odiseo_sylius_referrals_plugin.assigner.affiliate_referral", "assign"]
                    args: ["object"]
