odiseo_sylius_referrals_plugin_shop_partial_affiliate_statistics:
    path: /statistics
    methods: [GET]
    defaults:
        _controller: odiseo_sylius_referrals_plugin.controller.shop.statistics_affiliate

odiseo_sylius_referrals_plugin_shop_partial_affiliate_create_from_user:
    path: /create-from-user
    methods: [GET]
    defaults:
        _controller: odiseo_sylius_referrals_plugin.controller.shop.create_from_user_affiliate

odiseo_sylius_referrals_plugin_shop_partial_affiliate_create_from_product:
    path: /create-from-product/{id}
    methods: [POST]
    defaults:
        _controller: odiseo_sylius_referrals_plugin.controller.shop.create_from_product_affiliate
